import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type SupportedLanguage = 'mn' | 'en' | 'ja';

type Translations = Record<string, Record<SupportedLanguage, string>>;

const translations: Translations = {
  map_not_available: {
    mn: 'Газрын зураг web дээр боломжгүй',
    en: 'Map not available on web',
    ja: 'Webでは地図を利用できません',
  },
  views: {
    mn: 'үзсэн',
    en: 'views',
    ja: '閲覧',
  },
  language_label: {
    mn: 'Хэл',
    en: 'Language',
    ja: '言語',
  },
  mongolian: {
    mn: 'Монгол',
    en: 'Mongolian',
    ja: 'モンゴル語',
  },
  english: {
    mn: 'Англи',
    en: 'English',
    ja: '英語',
  },
  japanese: {
    mn: 'Япон',
    en: 'Japanese',
    ja: '日本語',
  },
  // NewTripScreen
  plan_new_trip: {
    mn: 'Шинэ аялал төлөвлөх',
    en: 'Plan a new trip',
    ja: '新しい旅行を計画する',
  },
  build_itinerary: {
    mn: 'Аяллын төлөвлөгөө боловсруулах',
    en: 'Build an itinerary and map out your upcoming travel plans',
    ja: '旅程を作成し、今後の旅行計画を地図に表示',
  },
  where_to: {
    mn: 'Хаашаа?',
    en: 'Where to?',
    ja: 'どこへ？',
  },
  example_locations: {
    mn: 'Жишээ: Улаанбаатар, Хөвсгөл, Говь',
    en: 'e.g., Paris, Hawaii, Japan',
    ja: '例：パリ、ハワイ、日本',
  },
  dates_optional: {
    mn: 'Огноо (сонголттой)',
    en: 'Dates (optional)',
    ja: '日付（オプション）',
  },
  start_date: {
    mn: 'Эхлэх огноо',
    en: 'Start date',
    ja: '開始日',
  },
  end_date: {
    mn: 'Дуусах огноо',
    en: 'End date',
    ja: '終了日',
  },
  invite_tripmate: {
    mn: '+ Аялагч урих',
    en: '+ Invite a tripmate',
    ja: '+ 旅行仲間を招待',
  },
  friends: {
    mn: 'Найзууд',
    en: 'Friends',
    ja: '友達',
  },
  start_planning: {
    mn: 'Төлөвлөлт эхлүүлэх',
    en: 'Start planning',
    ja: '計画を開始',
  },
  or_see_example: {
    mn: 'Эсвэл жишээг харах:',
    en: 'Or see an example for',
    ja: 'または例を見る：',
  },
  save: {
    mn: 'Хадгалах',
    en: 'Save',
    ja: '保存',
  },
  search_for_place: {
    mn: 'Газар хайх',
    en: 'Search for a place',
    ja: '場所を検索',
  },
  // HomeScreen
  plan_next_adventure: {
    mn: 'Дараагийн аяллаа төлөвлө',
    en: 'Plan your next adventure',
    ja: '次の冒険を計画',
  },
  create_new_trip_plan: {
    mn: 'Шинэ аяллын төлөвлөгөө үүсгэх',
    en: 'Create new trip plan',
    ja: '新しい旅行計画を作成',
  },
  continue_planning: {
    mn: 'Төлөвлөлтөө үргэлжлүүлэх',
    en: 'Continue Planning',
    ja: '計画を続ける',
  },
  see_all: {
    mn: 'Бүгдийг харах',
    en: 'See all',
    ja: 'すべて見る',
  },
  trip_to: {
    mn: 'Аялал:',
    en: 'Trip to',
    ja: '旅行先：',
  },
  places: {
    mn: 'газар',
    en: 'places',
    ja: '場所',
  },
  featured_guides: {
    mn: 'Хэрэглэгчдийн онцолсон гарын авлага',
    en: 'Featured guides from users',
    ja: 'ユーザーのおすすめガイド',
  },
  weekend_trips: {
    mn: 'Амралтын өдрийн аялал',
    en: 'Weekend trips',
    ja: '週末旅行',
  },
  popular_destinations: {
    mn: 'Алдартай газрууд',
    en: 'Popular destinations',
    ja: '人気の目的地',
  },
  featured: {
    mn: 'Онцлох',
    en: 'Featured',
    ja: 'おすすめ',
  },
  guide: {
    mn: 'Гарын авлага',
    en: 'Guide',
    ja: 'ガイド',
  },
  search_placeholder: {
    mn: 'Хаашаа явахыг хүсэж байна вэ?',
    en: 'Where do you want to go?',
    ja: 'どこへ行きたいですか？',
  },
  // AIChatScreen
  ai_assistant: {
    mn: 'AI Туслах',
    en: 'AI Assistant',
    ja: 'AIアシスタント',
  },
  messages_left: {
    mn: '4 мессеж үлдсэн. ',
    en: '4 messages left. ',
    ja: '残り4メッセージ。',
  },
  get_more: {
    mn: 'Илүү авах',
    en: 'Get more',
    ja: 'もっと取得',
  },
  ai_info_1: {
    mn: 'AI Туслах нь зөвхөн мэдээлэл өгдөг. Таны аяллын төлөвлөгөөнд засах эрхгүй.',
    en: 'The AI Assistant is purely informational. It does not have edit access to your trip plan.',
    ja: 'AIアシスタントは情報提供のみです。旅行計画を編集する権限はありません。',
  },
  ai_info_2: {
    mn: 'AI Туслах үүсгэсэн мэдээлэл бүрэн үнэн зөв биш байж болно.',
    en: 'Information generated by AI Assistant may not be fully accurate.',
    ja: 'AIアシスタントが生成した情報は完全に正確ではない場合があります。',
  },
  dont_know_what_to_ask: {
    mn: 'Юу асуухаа мэдэхгүй байна уу? Эдгээр жишээг туршиж үзээрэй:',
    en: "Don't know what to ask? Try these examples:",
    ja: '何を尋ねればいいか分かりませんか？これらの例を試してください：',
  },
  best_places_to_eat: {
    mn: 'Хамгийн сайн ресторанууд',
    en: 'Best places to eat in',
    ja: '最高のレストラン',
  },
  day_itinerary: {
    mn: '3 өдрийн төлөвлөгөө',
    en: '3 day itinerary to',
    ja: '3日間の旅程',
  },
  top_attractions: {
    mn: 'Гол сонирхолтой газрууд',
    en: 'Top attractions in',
    ja: '主な観光スポット',
  },
  ask_travel_questions: {
    mn: 'Аялалтай холбоотой асуулт асуу',
    en: 'Ask any travel related questions',
    ja: '旅行に関する質問をする',
  },
  curated_plan_title: {
    mn: 'Бидний зөвлөсөн аяллын төлөвлөгөө',
    en: 'Curated travel game plan',
    ja: '厳選された旅行プラン',
  },
  curated_plan_day_label: {
    mn: 'Өдрийн тойм',
    en: 'Day overview',
    ja: '日別サマリー',
  },
  curated_plan_highlights: {
    mn: 'Гол онцлох зүйлс',
    en: 'Highlights',
    ja: 'ハイライト',
  },
  curated_plan_prompt_cta: {
    mn: 'AI-аас дэлгэрэнгүй асуух',
    en: 'Ask AI for details',
    ja: 'AIに詳細を聞く',
  },
  curated_plan_expand: {
    mn: 'Дэлгэрэнгүй',
    en: 'Expand',
    ja: '展開する',
  },
  curated_plan_collapse: {
    mn: 'Хураах',
    en: 'Hide',
    ja: '閉じる',
  },
  curated_plan_details_duration: {
    mn: 'Төлөвлөсөн хугацаа',
    en: 'Duration',
    ja: '所要時間',
  },
  curated_plan_details_cost: {
    mn: 'Төсөв / Үнэ',
    en: 'Cost',
    ja: '費用',
  },
  curated_plan_details_weather: {
    mn: 'Цаг агаар',
    en: 'Weather',
    ja: '天候',
  },
  curated_plan_details_transport: {
    mn: 'Хэрхэн очих вэ',
    en: 'How to get there',
    ja: 'アクセス',
  },
  curated_plan_details_food: {
    mn: 'Хоол, кафе',
    en: 'Food & cafés',
    ja: '食事・カフェ',
  },
  curated_plan_details_activities: {
    mn: 'Юу хийх вэ',
    en: 'What to do',
    ja: '楽しみ方',
  },
  curated_plan_loading: {
    mn: 'Зургууд болон мэдээллийг ачааллаж байна…',
    en: 'Loading photos and details…',
    ja: '写真と詳細を読み込み中…',
  },
  curated_plan_opentripmap_title: {
    mn: 'Ойролцоох сонирхолтой газрууд (OpenTripMap)',
    en: 'Nearby highlights (OpenTripMap)',
    ja: '近くの見どころ (OpenTripMap)',
  },
  curated_plan_opentripmap_view_map: {
    mn: 'Газрын зураг харах',
    en: 'View on map',
    ja: '地図で見る',
  },
  curated_plan_opentripmap_prompt: {
    mn: 'AI-аас асуух',
    en: 'Ask AI',
    ja: 'AIに相談',
  },
  // ProfileScreen
  sign_out: {
    mn: 'Гарах',
    en: 'Sign Out',
    ja: 'サインアウト',
  },
  trips: {
    mn: 'Аяллууд',
    en: 'Trips',
    ja: '旅行',
  },
  guides: {
    mn: 'Гарын авлага',
    en: 'Guides',
    ja: 'ガイド',
  },
  sort: {
    mn: 'Эрэмбэлэх',
    en: 'Sort',
    ja: '並び替え',
  },
  no_trips_found: {
    mn: 'Аялал олдсонгүй. Шинэ аялал үүсгээрэй!',
    en: 'No trips found. Create a new trip!',
    ja: '旅行が見つかりません。新しい旅行を作成してください！',
  },
  in_days: {
    mn: 'өдрийн дараа',
    en: 'days',
    ja: '日後',
  },
  // MapScreen
  interactive_map: {
    mn: 'Интерактив газрын зураг',
    en: 'Interactive Map',
    ja: 'インタラクティブマップ',
  },
  open_in_google_maps: {
    mn: 'Google Maps дээр нээх',
    en: 'Open in Google Maps',
    ja: 'Googleマップで開く',
  },
  places_on_map: {
    mn: 'газар газрын зураг дээр',
    en: 'places on map',
    ja: 'マップ上の場所',
  },
  no_places_display: {
    mn: 'Харуулах газар байхгүй',
    en: 'No places to display',
    ja: '表示する場所がありません',
  },
  selected: {
    mn: 'Сонгогдсон',
    en: 'Selected',
    ja: '選択済み',
  },
  view_photos: {
    mn: 'зураг харах',
    en: 'photo',
    ja: '写真を見る',
  },
  photos: {
    mn: 'Зургууд',
    en: 'Photos',
    ja: '写真',
  },
  // Error messages
  please_select_location_date: {
    mn: 'Газар болон огнооны хүрээ сонгоно уу',
    en: 'Please select a location and date range',
    ja: '場所と日付範囲を選択してください',
  },
  user_not_authenticated: {
    mn: 'Хэрэглэгч нэвтрээгүй эсвэл имэйл дутуу',
    en: 'User not authenticated or email missing',
    ja: 'ユーザーが認証されていないか、メールアドレスが不足しています',
  },
  user_not_authenticated_simple: {
    mn: 'Хэрэглэгч нэвтрээгүй',
    en: 'User not authenticated',
    ja: 'ユーザーが認証されていません',
  },
  please_sign_in: {
    mn: 'Нэвтрэнэ үү',
    en: 'Please sign in',
    ja: 'サインインしてください',
  },
  // Common
  followers: {
    mn: 'ДАГАГЧ',
    en: 'FOLLOWERS',
    ja: 'フォロワー',
  },
  following: {
    mn: 'ДАГАЖ БАЙГАА',
    en: 'FOLLOWING',
    ja: 'フォロー中',
  },
  no_image_available: {
    mn: 'Зураг байхгүй',
    en: 'No image available',
    ja: '画像がありません',
  },
  unknown_place: {
    mn: 'Тодорхойгүй газар',
    en: 'Unknown Place',
    ja: '不明な場所',
  },
  // PlanTripScreen
  share: {
    mn: 'Хуваалцах',
    en: 'Share',
    ja: '共有',
  },
  overview: {
    mn: 'Тойм',
    en: 'Overview',
    ja: '概要',
  },
  itinerary: {
    mn: 'Төлөвлөгөө',
    en: 'Itinerary',
    ja: '旅程',
  },
  explore: {
    mn: 'Судлах',
    en: 'Explore',
    ja: '探索',
  },
  budget: {
    mn: 'Төсөв',
    en: 'Budget',
    ja: '予算',
  },
  wanderlog_level: {
    mn: 'Wanderlog түвшин:',
    en: 'Wanderlog level:',
    ja: 'Wanderlogレベル：',
  },
  basic: {
    mn: 'Энгийн',
    en: 'Basic',
    ja: '基本',
  },
  of: {
    mn: '-аас',
    en: 'of',
    ja: 'の',
  },
  add_reservation: {
    mn: 'Захиалга нэмэх',
    en: 'Add a reservation',
    ja: '予約を追加',
  },
  forward_email_reservation: {
    mn: 'Имэйл илгээх эсвэл захиалгын дэлгэрэнгүй мэдээлэл нэмэх',
    en: 'Forward an email or add reservation details',
    ja: 'メールを転送するか、予約詳細を追加',
  },
  skip: {
    mn: 'Алгасах',
    en: 'Skip',
    ja: 'スキップ',
  },
  start: {
    mn: 'Эхлэх',
    en: 'Start',
    ja: '開始',
  },
  explore_things_to_do: {
    mn: 'Хийх зүйлс судлах',
    en: 'Explore things to do',
    ja: 'やること探索',
  },
  add_places_from_blogs: {
    mn: 'Топ блогуудаас газрууд нэмэх',
    en: 'Add places from top blogs',
    ja: 'トップブログから場所を追加',
  },
  reservations_attachments: {
    mn: 'Захиалга болон хавсралтууд',
    en: 'Reservations and attachments',
    ja: '予約と添付ファイル',
  },
  flight: {
    mn: 'Нислэг',
    en: 'Flight',
    ja: 'フライト',
  },
  lodging: {
    mn: 'Буудал',
    en: 'Lodging',
    ja: '宿泊',
  },
  rental_car: {
    mn: 'Түрээсийн машин',
    en: 'Rental car',
    ja: 'レンタカー',
  },
  restaurant: {
    mn: 'Ресторан',
    en: 'Restaurant',
    ja: 'レストラン',
  },
  attachment: {
    mn: 'Хавсралт',
    en: 'Attachment',
    ja: '添付',
  },
  other: {
    mn: 'Бусад',
    en: 'Other',
    ja: 'その他',
  },
  notes: {
    mn: 'Тэмдэглэл',
    en: 'Notes',
    ja: 'メモ',
  },
  write_notes_placeholder: {
    mn: 'Ерөнхий тэмдэглэл бичээрэй, жишээ: хэрхэн явах, орон нутгийн зөвлөмж, сануулга',
    en: 'Write or paste general notes here, e.g. how to get around, local tips, reminders',
    ja: '一般的なメモをここに書くか貼り付けてください。例：移動方法、ローカルのヒント、リマインダー',
  },
  places_to_visit: {
    mn: 'Очих газрууд',
    en: 'Places to visit',
    ja: '訪問する場所',
  },
  no_places_added: {
    mn: 'Одоогоор газар нэмэгдээгүй',
    en: 'No places added yet',
    ja: 'まだ場所が追加されていません',
  },
  add_place: {
    mn: 'Газар нэмэх',
    en: 'Add a place',
    ja: '場所を追加',
  },
  discover_more_places: {
    mn: 'Илүү олон газар, үйл ажиллагаа олох',
    en: 'Discover more places and activities in',
    ja: 'より多くの場所やアクティビティを発見',
  },
  this_destination: {
    mn: 'энэ газар',
    en: 'this destination',
    ja: 'この目的地',
  },
  track_expenses: {
    mn: 'Энэ аяллын зардлаа хянах',
    en: 'Track your expenses for this trip',
    ja: 'この旅行の支出を追跡',
  },
  total: {
    mn: 'Нийт:',
    en: 'Total:',
    ja: '合計：',
  },
  add_new_expense: {
    mn: 'Шинэ зардал нэмэх',
    en: 'Add New Expense',
    ja: '新しい支出を追加',
  },
  paid_by: {
    mn: 'Төлсөн:',
    en: 'Paid by:',
    ja: '支払者：',
  },
  split: {
    mn: 'Хуваах:',
    en: 'Split:',
    ja: '分割：',
  },
  edit_expense: {
    mn: 'Зардал засах',
    en: 'Edit Expense',
    ja: '支出を編集',
  },
  description: {
    mn: 'Тайлбар',
    en: 'Description',
    ja: '説明',
  },
  enter_expense_description: {
    mn: 'Зардлын тайлбар оруулах',
    en: 'Enter expense description',
    ja: '支出の説明を入力',
  },
  category: {
    mn: 'Ангилал',
    en: 'Category',
    ja: 'カテゴリー',
  },
  amount: {
    mn: 'Дүн',
    en: 'Amount',
    ja: '金額',
  },
  enter_amount: {
    mn: 'Дүн оруулах',
    en: 'Enter amount',
    ja: '金額を入力',
  },
  paid_by_label: {
    mn: 'Төлсөн хүн',
    en: 'Paid By',
    ja: '支払者',
  },
  enter_name: {
    mn: 'Нэр оруулах',
    en: 'Enter name',
    ja: '名前を入力',
  },
  split_option: {
    mn: 'Хуваах сонголт',
    en: 'Split Option',
    ja: '分割オプション',
  },
  save_changes: {
    mn: 'Өөрчлөлт хадгалах',
    en: 'Save Changes',
    ja: '変更を保存',
  },
  add_expense: {
    mn: 'Зардал нэмэх',
    en: 'Add Expense',
    ja: '支出を追加',
  },
  dont_split: {
    mn: 'Хуваахгүй',
    en: "Don't Split",
    ja: '分割しない',
  },
  everyone: {
    mn: 'Бүгд',
    en: 'Everyone',
    ja: '全員',
  },
  shopping: {
    mn: 'Дэлгүүр',
    en: 'Shopping',
    ja: 'ショッピング',
  },
  activities: {
    mn: 'Үйл ажиллагаа',
    en: 'Activities',
    ja: 'アクティビティ',
  },
  sightseeing: {
    mn: 'Аялал жуулчлал',
    en: 'Sightseeing',
    ja: '観光',
  },
  invite_friends: {
    mn: 'Найзуудаа урих',
    en: 'Invite Friends',
    ja: '友達を招待',
  },
  collaborate_on_trip_plan: {
    mn: 'Аяллын төлөвлөгөөгөө хамтдаа боловсруулаарай',
    en: 'Collaborate on your trip plan together',
    ja: '一緒に旅行計画を立てましょう',
  },
  copy_invite_link: {
    mn: 'Урилгын холбоос хуулах',
    en: 'Copy Invite Link',
    ja: '招待リンクをコピー',
  },
  invite_link_copied: {
    mn: 'Урилгын холбоос хуулагдлаа!',
    en: 'Invite link copied!',
    ja: '招待リンクをコピーしました！',
  },
  trip_overview: {
    mn: 'Аяллын тойм',
    en: 'Trip Overview',
    ja: '旅行の概要',
  },
  total_days: {
    mn: 'Нийт өдөр',
    en: 'Total Days',
    ja: '合計日数',
  },
  saved_places_label: {
    mn: 'Хадгалсан газрууд',
    en: 'Saved Places',
    ja: '保存した場所',
  },
  planned_activities_label: {
    mn: 'Төлөвлөсөн үйл ажиллагаа',
    en: 'Planned Activities',
    ja: '計画されたアクティビティ',
  },
  total_spent_label: {
    mn: 'Нийт зарцуулсан',
    en: 'Total Spent',
    ja: '合計支出',
  },
  days_stats: {
    mn: 'ӨДӨР',
    en: 'DAYS',
    ja: '日',
  },
  places_stats: {
    mn: 'ГАЗАР',
    en: 'PLACES',
    ja: '場所',
  },
  planned_stats: {
    mn: 'ТӨЛӨВЛӨСӨН',
    en: 'PLANNED',
    ja: '計画済み',
  },
  budget_stats: {
    mn: 'ТӨСӨВ',
    en: 'BUDGET',
    ja: '予算',
  },
  plan_itinerary: {
    mn: 'Төлөвлөгөө гаргах',
    en: 'Plan Itinerary',
    ja: '旅程を計画',
  },
  organize_daily_activities: {
    mn: 'Өдрийн үйл ажиллагаануудаа зохион байгуул',
    en: 'Organize your daily activities',
    ja: '毎日のアクティビティを整理',
  },
  start_planning_cta: {
    mn: 'Төлөвлөж эхлэх',
    en: 'Start Planning',
    ja: '計画を開始',
  },
  explore_now_cta: {
    mn: 'Одоо судлах',
    en: 'Explore Now',
    ja: '今すぐ探索',
  },
  discover_new_places: {
    mn: 'Шинэ газрууд нээж илрүүл',
    en: 'Discover new places',
    ja: '新しい場所を発見',
  },
  total_budget: {
    mn: 'Нийт төсөв',
    en: 'Total Budget',
    ja: '総予算',
  },
  transactions: {
    mn: 'Гүйлгээнүүд',
    en: 'Transactions',
    ja: '取引',
  },
  add_new: {
    mn: 'Шинээр нэмэх',
    en: 'Add New',
    ja: '新規追加',
  },
  delete: {
    mn: 'Устгах',
    en: 'Delete',
    ja: '削除',
  },
  transport: {
    mn: 'Тээвэр',
    en: 'Transport',
    ja: '交通',
  },
  drinks: {
    mn: 'Ундаа',
    en: 'Drinks',
    ja: '飲み物',
  },
  food: {
    mn: 'Хоол',
    en: 'Food',
    ja: '食べ物',
  },
  transportation: {
    mn: 'Тээвэр',
    en: 'Transportation',
    ja: '交通',
  },
  entertainment: {
    mn: 'Энтертайнмент',
    en: 'Entertainment',
    ja: 'エンターテインメント',
  },
  miscellaneous: {
    mn: 'Бусад',
    en: 'Miscellaneous',
    ja: 'その他',
  },
  user_or_trip_id_missing: {
    mn: 'Хэрэглэгч эсвэл аяллын ID дутуу',
    en: 'User or trip ID missing',
    ja: 'ユーザーまたは旅行IDが不足しています',
  },
  hours_unavailable: {
    mn: 'Цагийн мэдээлэл байхгүй',
    en: 'Hours unavailable',
    ja: '営業時間不明',
  },
  ai_suggested_places: {
    mn: 'AI-ийн санал болгосон газрууд',
    en: 'AI-Suggested Places',
    ja: 'AI提案の場所',
  },
  select_date_for_itinerary: {
    mn: 'Энэ газрыг төлөвлөгөөнд нэмэхийн тулд огноо сонгоно уу',
    en: 'Please select a date to add this place to the itinerary',
    ja: 'この場所を旅程に追加するには日付を選択してください',
  },
  generate_itinerary_ai: {
    mn: '✨ AI ашиглан төлөвлөгөө үүсгэх',
    en: '✨ Generate Itinerary (AI)',
    ja: '✨ AIで旅程を生成',
  },
  use_ai_create_itinerary: {
    mn: '✨ AI ашиглан төлөвлөгөө бүтээх',
    en: '✨ Use AI to Create Itinerary',
    ja: '✨ AIを使用して旅程を作成',
  },
  generating_itinerary: {
    mn: 'Төлөвлөгөө үүсгэж байна…',
    en: 'Generating Itinerary…',
    ja: '旅程を生成中…',
  },
  fetching_ai_suggestions: {
    mn: 'AI санал аваж байна...',
    en: 'Fetching AI Suggestions...',
    ja: 'AI提案を取得中...',
  },
  auto_fill_day: {
    mn: '✈️ Өдрийг автоматаар бөглөх',
    en: '✈️ Auto-fill day',
    ja: '✈️ 日を自動入力',
  },
  optimize_route: {
    mn: '🗺️ Замыг оновчтой болгох',
    en: '🗺️ Optimize route',
    ja: '🗺️ ルートを最適化',
  },
  add_subheading: {
    mn: 'Дэд гарчиг нэмэх',
    en: 'Add subheading',
    ja: 'サブ見出しを追加',
  },
  no_activities_added: {
    mn: 'Энэ өдөрт үйл ажиллагаа нэмэгдээгүй байна',
    en: 'No activities added for this date',
    ja: 'この日付にアクティビティが追加されていません',
  },
  popular_places: {
    mn: 'Алдартай газрууд',
    en: 'Popular Places',
    ja: '人気の場所',
  },
  quick_actions: {
    mn: 'Хурдан үйлдлүүд',
    en: 'Quick Actions',
    ja: 'クイックアクション',
  },
  ask_ai: {
    mn: 'AI-аас асуух',
    en: 'Ask AI',
    ja: 'AIに尋ねる',
  },
  no_address_available: {
    mn: 'Хаяг байхгүй',
    en: 'No address available',
    ja: '住所がありません',
  },
  located_in: {
    mn: 'Байрлал:',
    en: 'Located in',
    ja: '所在地：',
  },
  nice_place_to_visit: {
    mn: 'Очих сайхан газар.',
    en: 'A nice place to visit.',
    ja: '訪れるのに良い場所。',
  },
  unnamed_trip: {
    mn: 'Нэргүй аялал',
    en: 'Unnamed Trip',
    ja: '名前のない旅行',
  },
  na: {
    mn: 'Тодорхойгүй',
    en: 'N/A',
    ja: '該当なし',
  },
  address: {
    mn: 'Хаяг',
    en: 'Address',
    ja: '住所',
  },
  todays_hours: {
    mn: 'Өнөөдрийн цагийн хуваарь',
    en: "Today's Hours",
    ja: '今日の営業時間',
  },
  phone: {
    mn: 'Утас',
    en: 'Phone',
    ja: '電話',
  },
  error: {
    mn: 'Алдаа',
    en: 'Error',
    ja: 'エラー',
  },
};

Object.assign(translations, {
  greeting_morning: {
    mn: 'Өглөөний мэнд',
    en: 'Good morning',
    ja: 'おはようございます',
  },
  greeting_afternoon: {
    mn: 'Өдрийн мэнд',
    en: 'Good afternoon',
    ja: 'こんにちは',
  },
  greeting_evening: {
    mn: 'Оройн мэнд',
    en: 'Good evening',
    ja: 'こんばんは',
  },
  sign_in_title: {
    mn: 'Нэвтрэх',
    en: 'Sign in',
    ja: 'サインイン',
  },
  sign_in_subtitle: {
    mn: 'Монгол орноор хамтдаа аялацгаая',
    en: 'Plan memorable journeys across Mongolia',
    ja: 'モンゴル各地の旅を計画しましょう',
  },
  sign_up_title: {
    mn: 'Шинэ бүртгэл',
    en: 'Create account',
    ja: 'アカウント作成',
  },
  sign_up_subtitle: {
    mn: 'MonGoTrip-д тавтай морилно уу',
    en: 'Start building smarter Mongolia trips',
    ja: 'モンゴル旅行をかしこく始めましょう',
  },
  email_label: {
    mn: 'Имэйл хаяг',
    en: 'Email address',
    ja: 'メールアドレス',
  },
  password_label: {
    mn: 'ÐÑƒÑƒÑ† Ò¯Ð³',
    en: 'Password',
    ja: 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰',
  },
  continue_cta: {
    mn: 'Ò®Ñ€Ð³ÑÐ»Ð¶Ð»Ò¯Ò¯Ð»ÑÑ…',
    en: 'Continue',
    ja: 'ç¶šè¡Œ',
  },
  sign_up_cta: {
    mn: 'Ð‘Ò¯Ñ€Ñ‚Ð³Ò¯Ò¯Ð»ÑÑ…',
    en: 'Create account',
    ja: 'ç™»éŒ²ã™ã‚‹',
  },
  sign_in_with_google: {
    mn: 'Google-ÑÑÑ€ Ð½ÑÐ²Ñ‚Ñ€ÑÑ…',
    en: 'Sign in with Google',
    ja: 'Google ã§ã‚µã‚¤ãƒ³ã‚¤ãƒ³',
  },
  no_account_yet: {
    mn: 'Ð‘Ò¯Ñ€Ñ‚Ð³ÑÐ»Ð³Ò¯Ð¹ ÑŽÑƒ?',
    en: "Don't have an account?",
    ja: 'ã‚¢ã‚«ã‚¦ãƒ³ãƒˆãŒã‚ã‚Šã¾ã›ã‚“ã‹ï¼Ÿ',
  },
  have_account: {
    mn: 'ÐÐ»ÑŒ Ñ…ÑÐ´Ð¸Ð¹Ð½ Ð±Ò¯Ñ€Ñ‚Ð³ÑÐ»Ñ‚ÑÐ¹ ÑŽÑƒ?',
    en: 'Already have an account?',
    ja: 'ã™ã§ã«ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã‚’ãŠæŒã¡ã§ã™ã‹ï¼Ÿ',
  },
  create_account: {
    mn: 'Ð‘Ò¯Ñ€Ñ‚Ð³Ò¯Ò¯Ð»ÑÑ…',
    en: 'Create account',
    ja: 'ã‚¢ã‚«ã‚¦ãƒ³ãƒˆä½œæˆ',
  },
  verify_email: {
    mn: 'Ð˜Ð¼ÑÐ¹Ð» Ð±Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑƒÑƒÐ»Ð°Ñ…',
    en: 'Verify email',
    ja: 'ãƒ¡ãƒ¼ãƒ«èªè¨¼',
  },
  verification_code: {
    mn: 'Ð‘Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑƒÑƒÐ»Ð°Ñ… ÐºÐ¾Ð´',
    en: 'Verification code',
    ja: 'èªè¨¼ã‚³ãƒ¼ãƒ‰',
  },
  verify_cta: {
    mn: 'Ð‘Ð°Ñ‚Ð°Ð»Ð³Ð°Ð°Ð¶ÑƒÑƒÐ»Ð°Ñ…',
    en: 'Verify',
    ja: 'èªè¨¼ã™ã‚‹',
  },
  verify_email_help: {
    mn: 'Ð¢Ð°Ð½Ñ‹ Ð¸Ð¼ÑÐ¹Ð» Ñ€Ò¯Ò¯ Ð¸Ð»Ð³ÑÑÑÑÐ½ 6 Ð¾Ñ€Ð¾Ð½Ñ‚Ð¾Ð¹ ÐºÐ¾Ð´Ñ‹Ð³ Ð¾Ñ€ÑƒÑƒÐ»Ð½Ð° ÑƒÑƒ',
    en: 'Enter the 6-digit code we sent to your email',
    ja: 'ãƒ¡ãƒ¼ãƒ«ã«é€ä¿¡ã—ãŸ6æ¡ã®ã‚³ãƒ¼ãƒ‰ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„',
  },
  loading_action: {
    mn: 'Ð£Ð½ÑˆÐ¸Ð¶ Ð±Ð°Ð¹Ð½Ð°...',
    en: 'Loading...',
    ja: 'èª­ã¿è¾¼ã¿ä¸­...',
  },
  verifying_action: {
    mn: 'Ð¨Ð°Ð»Ð³Ð°Ð¶ Ð±Ð°Ð¹Ð½Ð°...',
    en: 'Verifying...',
    ja: 'ç¢ºèªä¸­...',
  },
});

type LanguageContextValue = {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>('mn');

  useEffect(() => {
    AsyncStorage.getItem('app_language')
      .then((stored) => {
        if (stored === 'mn' || stored === 'en' || stored === 'ja') {
          setLanguage(stored);
        }
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    AsyncStorage.setItem('app_language', language).catch(() => {});
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key) => (translations as Record<string, Record<SupportedLanguage, string>>)[key]?.[language] ?? String(key),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}


